version: '3'

services:
  web:
    stdin_open: true
    restart: always
    environment: 
      TZ: Asia/Tokyo
    build:
      context: .
    volumes:
      - .:/usr/src
    command: bash -c "cd dashboard && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000