# Generated by Django 2.2.15 on 2020-11-01 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=2, verbose_name='area')),
                ('tariff', models.CharField(max_length=2, verbose_name='tariff')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Consumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='datetime')),
                ('consumption', models.FloatField(verbose_name='consumption')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumption.User', verbose_name='user')),
            ],
            options={
                'db_table': 'consumption',
            },
        ),
    ]
